spring:
  datasource:
    url: jdbc:postgresql://db:5432/supportdb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MiClaveSuperSecreta123456789012345678901234567890
